DROP TABLE PERSON;
DROP SEQUENCE person_seq;


CREATE SEQUENCE person_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PERSON (
  "ID" NUMBER(*,0) NOT NULL ENABLE,
  "FIRST_NAME" VARCHAR2(255 BYTE),
  "LAST_NAME" VARCHAR2(255 BYTE),
  CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID"));